docker-php/docker-php

src/Docker/Http/DockerClient.php
This allows you to convert the options array to a stream context resource
Use-case for example:
Symfony DI service:
```yml
services:
docker.client:
class: Docker\Http\DockerClient
factory: Docker\Http\DockerClient::createWithContext
arguments:
- ~
- %docker_entrypoint%
-
ssl:
local_cert: '%docker_cert_path%/comb.pem'
- true
```
=> Add DockerClient::createWithContext to convert stream context options

src/Docker/Manager/ContainerManager.php, src/Docker/Manager/ImageManager.php
Images need not have a name and tag, so __toString(9 may return "<none>:<none>"
hence one needs to the the id (e.g. 5a6ad7a9472d661def485ec19146a69f7ae1a78d3064c9d0cc18b44fe445f279).
I came across this when trying to list all images as follows. the inspect() line will not work without this fix.
$images = $imagemgr->findAll();
foreach ($images as $image) {
$data=$imagemgr->inspect($image);
print($image->__toString() . " " . $data['Created'] . " " . $image->getID() . "\n");
}
Also: 
- Improved error string. Doc: correct return.
Could we briefly talk about these two lines, before finalising the commit? See #78 
$image->setId($data['Id']);
// @TODO Add extra info on image
=> ImageManager::inspect(), use id not repo:tag to identify. 

docs/basic.md, docs/container.md, docs/image/find.md, docs/image/pull.md, docs/index.md, docs/installation.md, mkdocs.yml
Work in progress on the documentation:
* Use readthedocs (for versioning purpose)
* Separate Container / Image concept
* Add some cookbooks on how to do A ?, how to do B ? ....
This branch is currently building at: http://docker-php.readthedocs.org/en/feature-readthedocs (manual trigger for the moment)
ping @ubermuda :)
=> [WIP] Add documentation on read the docs

.travis.yml
I think we should disable hhvm while it fails..doesn’t help us & just uses up Travis resources.
=> Travis changes - Symfony stable + disable hhvm

src/Docker/Context/Context.php
I think this was copied from `ContextBuilder` or used previously but is now unused.
=> Remove unused Symfony Filesystem from Docker\Context

docs/container.md, docs/image/remove.md, src/Docker/Manager/ContainerManager.php, src/Docker/Manager/ImageManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php, src/Docker/Tests/Manager/ImageManagerTest.php
From #30 `Utility function > Allow to easy remove a bunch of containers / image` I created a very basic method called `removeContainers` which takes an array of container ids (strings) or `Docker\Container` instances and passes them to the existing `remove` method. Same for ImageManager `deleteImages` expecting an array of image ids (strings..use ImageManager->find if you want to use the repo+tag) or `Docker\Image` instances.
Btw: Should we add a `findById` method to the ImageManager for simplicity? 
```php
$image = new Image();
$image->setId($imageId);
```
might seem odd to some developers.
=> Add removeContainers to ContainerManager

README.md
Since 37aaf6c1ad0165b7129460a521b2fdb06f411409 there is no usage.md file to point to. So the "the documentation" link sends to a 404.
The links on the index.md files does not work, and the http://docker-php.readthedocs.org/ page does not seems to be ready so, we just link to the docs folder on github.
=> Fix link to the documentation

.travis.yml
After @joelwurtz already tried several ways to fix docker on the `fix/travis` branch I’m giving it a shot too.
Just some notes:
Travis CI changed the cookbooks which might have caused the issues..compare: https://github.com/travis-ci/travis-cookbooks/compare/5736160...23bb455#commit_comments_bucket
I noticed something REALLY unnecessary: the env matrix isn’t actually used!! This will be fixed later.
=> Fix Travis builds (making Docker run again and actually use Symfony version)

src/Docker/Manager/ImageManager.php, src/Docker/Tests/Manager/ImageManagerTest.php
Allows `$imageManager->findAll(['all' => true]);` and `$imageManager->findAll(['dangling' => true]);`
See http://docs.docker.com/reference/api/docker_remote_api_v1.17/#list-images
Fixes #97
=> Add optional parameters to ImageManager::findAll

docs/container.md, src/Docker/Manager/ContainerManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php
The latest API allows containers to be renamed.
http://docs.docker.com/reference/api/docker_remote_api_v1.17/#rename-a-container
Example usage:
```
$container = $manager->find('mycontainer');
$ret = $manager->rename($container, 'mynewcontainer');
```
=> New api function: Rename a container

src/Docker/Manager/ContainerManager.php
Small fixes in `client` methods invocation.
- `wait` parameter fix. It should be passed to options, not to query.
- `volumes` (`v`) mistake fix.
- CS fixes.
=> Fixes in ContainerManager. Volumes parameter, wait parameter, CS fixes

src/Docker/Manager/ImageManager.php
This PR add a `push` method on the image manager that allows to push an image to a registry.
=> Allow to push image

src/Docker/Http/Stream/Filter/Event.php
Oftentimes our executions would seem to bail out. They would continue to run, but the stream would be severed and we could not see the output from the stream. Traced it to the data variable being overwritten, and thus the buffer not properly being updated for the next bucket.
=> Fixes disconnected vnd.docker.raw-streams output

src/Docker/Container.php, src/Docker/Tests/ContainerTest.php
Docker allows a little more characters to names, such as dots, and forbids names to begin with - or _.
This PR improves the regexp name. It includes unit tests.
=> Extending container name validation pattern to [a-zA-Z0-9][a-zA-Z0-9_.-]

src/Docker/Manager/ImageManager.php
The API expects a "filters" parameter to be a json encoded format.
This fix ensures only dangling images are returned. Tested on API v1.20 by running `docker images -f dangling=true -a` and comparing the results with those returned by `fetchAll(true)`.
https://docs.docker.com/reference/api/docker_remote_api_v1.17/#list-images
=> Fixing $dangling parameter in findAll (updated)

src/Docker/PortCollection.php, src/Docker/Tests/PortCollectionTest.php
Unlike ExposedPort, HostConfig["PortBindings"] allows to bind the same port to multiple other ports, as it is an array. As the current use of the array_merge will overwrite existing key when creating spec, it is mandatory to use array_merge_recursive to allow reusing multiple times the same port/protocol tuple.
Includes a unit test to cover the issue.
=> Fix merging ports to allow multiple use of the same port/protocol tuple.

src/Docker/Manager/ContainerManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php
I was inspecting the test suite, and since this particular test randomly passed and failed, I figured I'd give a try at stabilising it.
The former test might have (theoretically) done a better job at testing that the container *actually* restarts, but isn't that the job of docker's test suite? Instead, our only job here is to ensure that the docker daemon received the restart request, and handled it, which this test does.
=> Fix `ContainerManagerTest#testRestart`

src/Docker/Manager/ContainerManager.php
- adds the since parameter for docker logs
- performs an additional check which streams are selected and throws an exception if none is selected
Note, if you don't select a stream, you get an empty response, the real error message is available in `response.output` (but maybe not in event request)
Snip from `var_dump($response)`:
```
["response.output"]=>
array(1) {
[0]=>
array(1) {
[0]=>
object(Closure)#75 (3) {
["static"]=>
array(1) {
["callback"]=>
object(Closure)#79 (3) {
["static"]=>
array(1) {
["logs"]=>
&array(1) {
[0]=>
array(2) {
["type"]=>
NULL
["output"]=>
string(52) "Bad parameters: you must choose at least one stream
"
}
}
}
```
=> Feature: update logs

src/Docker/Http/Adapter/DockerAdapter.php
I got several empty error messages, like:
```
Exception 'Docker\Exception\APIException' with message ''
```
With this change you get:
```
Exception 'Docker\Exception\APIException' with message 'Client error response [url] /containers/bcb617efada6/logs?follow=0&stdout=0&stderr=0&timestamps=0&tail=all [status code] 400 [reason phrase] Bad Request'
```
=> update request excpetion to show message

README.md, docker-compose.yml
**Note: This PR is not complete yet, it's primarily a code example atm.**
How about an improved dockerized testing solution? While creating some PRs I also tried to run the tests, but faced some glitches, such as certificate setup and missing images for testing.
The process itself can be improved - for sure. But here's the basic idea: Just run a pre-configured docker container for the tests. 
The image is the [base image](https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-5.6-fpm) from our PHP app template, but just serves as a PHP cli+composer here - it's also configured to run a PHP app in `/app`.
It would also be possible to run [Codeception](http://codeception.com) tests with this image.
By mounting the `docker.sock` file we can use the …
=> [Proposal] docker-compose testing

composer.json
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Can only install one of: php-http/message[1.0.x-dev, 0.2.0].
- Can only install one of: php-http/message[v0.2.1, 1.0.x-dev].
- php-http/plugins dev-master requires php-http/message ^1.0 -> satisfiable by php-http/message[1.0.x-dev].
- Installation request for php-http/plugins dev-master -> satisfiable by php-http/plugins[dev-master].
- Installation request for php-http/message ^0.2@dev -> satisfiable by php-http/message[0.2.0, v0.2.1].
```
fix composer dependency for php-http/message
=> Composer update php-http/message version

docker-swagger.json, generated/Resource/ExecResource.php, tests/Manager/ExecManagerTest.php
ExecManager::find() shoud perform a GET request to /exec/(id)/json. It currently performs a POST request.
=> Fix method of /exec/(id)/json call

src/DockerClient.php
@joelwurtz , can you look into this?
The DockerClient::createFromEnv not producing correct connection param.
Current output is:
```
Array
(
[remote_socket] => tcp://192.168.99.100:2376
[ssl] => Array
(
[cafile] => /Users/smacalalag/.docker/machine/machines/default/ca.pem
[local_cert] => /Users/smacalalag/.docker/machine/machines/default/cert.pem
[local_pk] => /Users/smacalalag/.docker/machine/machines/default/key.pem
[peer_name] => boot2docker
)
)
```
Should be:
```
Array
(
[remote_socket] => tcp://192.168.99.100:2376
[ssl] => 1
[stream_context_options] => Array
(
[ssl] => Array
(
[cafile] => /Users/smacalalag/.docker/machine/machines/default/ca.pem
[local_cert] => /Users/smacalalag/.docker/machine/machines/default/cert.pem
[local_pk] => …
```
=> Adjust options when DOCKER_TLS_VERIFY is enabled

docs/cookbook/container-run.md
Without this it takes some hunting through the source to find the correct paths.
=> used namespaces in documentation example

docker-swagger.json, generated/Resource/VolumeResource.php
The "Content-Type" header must be set to "application/json" otherwise it doesn't work.
=> Added missing Content-Type header for volume creation

docker-swagger.json, generated/Model/ContainerConfig.php, generated/Normalizer/ContainerConfigNormalizer.php
This patch allows for the ExposedPorts in ContainerConfig to be null - when no ports are exposed in the container
fixes #206
=> Allow ExposedPorts to be null in ContainerConfig

docs/cookbook/container-run.md
I know its a small thing but for a moment it really confused me. I assume its meant to be json not son.
=> Changed docs to say JSON log driver

src/DockerClient.php
This header is now required.
See https://github.com/docker/docker/blob/master/docs/breaking_changes.md#engine-112
=> Add host header to fix compatibility with docker 1.12

src/Stream/MultiJsonStream.php, tests/Stream/MultiJsonStreamTest.php
This patch fixes issues in dealing with escaped characters in side quoted strings.
Note that 1.x also has this bug.
=> Added tests and fixed escape bugs in JsonMultiStream

docs/cookbook/container-run.md
ContainersCreatePostBody::setNames() does not exist. Set name unique name with containerCreate()
=> Fix `Reading logs in real time` example

src/Client/AmpArtaxStreamEndpoint.php, src/Client/AmpArtaxStreamEndpointTrait.php, src/Client/ProvideAmpArtaxClientOptions.php, src/DockerAsync.php, src/Endpoint/SystemEvents.php, src/Stream/ArtaxCallbackStream.php, tests/DockerAsyncTest.php
This feature make it possible to consume docker system events asynchronously using the `DockerAsync` client implementation.
Fixes issue #312 
```php
<?php
// filename : ./examples/listen-to-docker-events-async.php
use Docker\DockerAsync;
use Docker\Stream\ArtaxCallbackStream;
require dirname(__DIR__) . '/vendor/autoload.php';
Amp\Loop::run(function () {
$docker = DockerAsync::create();
/** @var ArtaxCallbackStream $events */
$events = yield $docker->systemEvents();
$events->onFrame(function ($event): void {
// Do something with the docker event
// var_dump($event);
});
// Start listening to Docker events
$events->listen();
// Close the request when a SIGINT signal is received
Amp\Loop::onSignal(SIGINT, function (string $watcherId) use ($events) {
$events->cancel(); …
```
=> feat: Consume Docker system events asynchronously
