docker-php/docker-php

src/Docker/Container.php, src/Docker/Context/Context.php, src/Docker/Context/ContextBuilder.php, src/Docker/Docker.php, src/Docker/Exception/ImageNotFoundException.php, src/Docker/Http/Adapter/DockerAdapter.php, src/Docker/Http/DockerClient.php, src/Docker/Http/Stream/Filter/Event.php, src/Docker/Http/Stream/Filter/OutputEvent.php, src/Docker/Http/Stream/InteractiveStream.php, src/Docker/Image.php, src/Docker/Manager/ContainerManager.php, src/Docker/Manager/ImageManager.php, src/Docker/PortCollection.php, src/Docker/Tests/Manager/ContainerManagerTest.php
Going through the code I noticed some inconsistencies and fixed them.
=> Update Phpdoc and fix array syntax inconsistencies

src/Docker/Manager/ImageManager.php
=> Remove reference to undefined/old StreamCallbackInterface

README.md
There was incorrect link. Just fixed
=> Update link to Docker docs into README

src/Docker/Manager/ContainerManager.php, src/Docker/Manager/ImageManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php, src/Docker/Tests/Manager/ImageManagerTest.php
...with the Docker API.
Fixes #85
=> Rename ImageManager::delete to ImageManager::remove to be more consistent

docs/basic.md, docs/image/pull.md, docs/index.md, docs/installation.md
Working on the docs..feedback more than welcome!
More usage examples are coming over the next few days
=> Docs: Improve installation, add image pull, small changes

docs/container.md, src/Docker/Manager/ContainerManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php
=> exec() and execstart() in ContainerManager

src/Docker/Manager/ImageManager.php, src/Docker/Tests/Manager/ImageManagerTest.php
=> Add tag api call for images

src/Docker/Manager/ImageManager.php, src/Docker/Tests/Manager/ImageManagerTest.php
Add api call history for an image
=> Add api call history for an image

docs/container.md, src/Docker/Manager/ContainerManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php
=> Copy files or folders from a container

src/Docker/Image.php, src/Docker/Manager/ImageManager.php
Hey,
I've added created date field to image entity.
=> Added created date field to image entity

.scrutinizer.yml, docs/container.md, src/Docker/Manager/ContainerManager.php, src/Docker/Tests/Manager/ContainerManagerTest.php
Just one line of code to add support for the "force" parameter when removing a container.
=> Add support to force container removal

src/DockerClient.php
A quick look into the constructor of DecoderPlugin shows, that you cannot provide a boolean here.
=> Fix construction of decoder plugin

docker-swagger.json, generated/Resource/ImageResource.php
Some imageManager methods where missing a required name parameter like find(), history(), remove()
=> fix missing required param 'name' is some imageResource methods

docker-swagger.json
I wanted to generate code from this spec so I made it validate
=> Make swagger spec validate

docker-swagger.json, generated/Resource/ImageResource.php, src/Manager/ImageManager.php
The swagger JSON did not match the actual Docker API specification regarding how you pass authentication data to the image create call.
=> Fixed a bug in the swagger doc that resulted in an inability to pull from a protected registry

src/Context/ContextBuilder.php, tests/Context/ContextBuilderTest.php
Hi,
I added COPY, ENV, WORKDIR, EXPOSE methods to the ContextBuilder and added tests.
Thank for the good work on docker-php !
=> Add COPY, ENV, WORKDIR, EXPOSE to ContextBuilder

docker-swagger.json, generated/Model/HostConfig.php, generated/Model/LogConfig.php, generated/Normalizer/HostConfigNormalizer.php, generated/Normalizer/LogConfigNormalizer.php, generated/Resource/NetworkResource.php
Fixes some issues related to 
- Logging
- Multihostnetwork
- Container search with containers that have portbindings defined
=> Fixes some api related issues

docker-swagger.json, generated/Model/NetworkConfig.php, generated/Normalizer/NetworkConfigNormalizer.php
Without this change I get an exception in `find` for not running containers because `Ports` in `NetworkSettings` is `null`.
=> Allow Ports in NetworkConfig to be null

src/Context/ContextBuilder.php
Add support for CMD, ENTRYPOINT, USER and VOLUME commands in ContextBuilder.
=> Extended ContextBuilder

docker-swagger.json, generated/Model/Network.php, generated/Normalizer/NetworkNormalizer.php
The containers in the network model can be null if there are no containers linked to it.
Also, the network has labels, Its not documented but when inspecting the raw output it had the labels key.
=> Fix null containers and add labels to Network

docs/index.md
Assuming the project readme is more up to date than the docs :D
=> Reflect API support up to version 1.24

composer.json, generated/Resource/ContainerResource.php, generated/Resource/ExecResource.php, generated/Resource/ImageResource.php, generated/Resource/MiscResource.php, generated/Resource/NetworkResource.php, generated/Resource/NodeResource.php, generated/Resource/ServiceResource.php, generated/Resource/SwarmResource.php, generated/Resource/TaskResource.php, generated/Resource/VolumeResource.php, src/Manager/ContainerManager.php, src/Manager/ImageManager.php
Hi,
The new OpenApi has some minor changes in the import path. This pull request fixes them.
Yours truly,
Iman Tabrizian
=> Updates imports from OpenApi to new version

docker-swagger.json, generated/Model/HostConfig.php, generated/Normalizer/HostConfigNormalizer.php
Properties added: Tmpfs, MemoryReservation, KernelMemory, and CpuQuota
=> Add missing properties to HostConfig

src/Context/ContextBuilder.php, tests/Context/ContextBuilderTest.php
=> Support multiple FROM in ContextBuilder.

src/Context/ContextBuilder.php, tests/Context/ContextBuilderTest.php
=> Add support for adding files from disk and streams

src/Context/ContextBuilder.php, tests/Context/ContextBuilderTest.php
See #292; this is a naive implementation that always traverses (directory) symlinks
=> Basic implementation of symlink traversal

docs/async.md
Use punctuation for clarity and correct a verb conjugation
=> Grammar update

docs/basic.md
This corrects a spelling error
=> Correct spelling error

docs/installation.md
This is a minor grammar/spelling fix PR to help increase clarity in the `installation` page.
=> Grammar and spelling fixes

docs/connection.md
This is just a minor grammar update to the connection instructions
=> Update grammar - minor

CONTRIBUTING.md, docs/installation.md, src/DockerAsyncClient.php, src/DockerClientFactory.php, tests/DockerClientFactoryTest.php
=> Fixed typos

docs/cookbook/build-image.md
=> Fix grammatical error
